sudo: false
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script:
  - bundle exec script/cibuild
  - bundle exec script/cibuild-lint
